id: IF3696845
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:51:39+00:00'
last_modified: '2022-06-08T09:26:19.767041+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10786
  title: དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག་ཟུར་དུ་བཀོད་པ་དང་བསྡུས་པའི་བསྡོམས་ཚིག་བློ་གསལ་དགའ་བསྐྱེད་དང་འགྲེལ་པ་ལུང་རིགས་སྨྲ་བའི་རྒྱན་མཆོག་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CD60:
      image_group_id: I1KG11761
      title: ''
      total_pages: 596
      order: 1
      base_file: CD60.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
