id: opecha:P009215
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10786
  title: དགེ་འདུན་ཉི་ཤུའི་རྣམ་གཞག་ཟུར་དུ་བཀོད་པ་དང་བསྡུས་པའི་བསྡོམས་ཚིག་བློ་གསལ་དགའ་བསྐྱེད་དང་འགྲེལ་པ་ལུང་རིགས་སྨྲ་བའི་རྒྱན་མཆོག་སོགས།
  volume: ''
  author: ''
